//Contains members data
export const membersData2021 = [
  {
    tag: "Batch 2021",
    name: "Mayank",
    batch: "MCA'21",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2021/Mayank_21.jpg",
  },
  {
    tag: "Batch 2021",
    name: "Tanmoy",
    batch: "MSC'20",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2021/Tanmoy_20.jpg",
  },
  {
    tag: "Batch 2021",
    name: "Cheshta",
    batch: "MCA'21",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2021/Cheshta_21.jpg",
  },
  {
    tag: "Batch 2021",
    name: "UTSA",
    batch: "MSC'20",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2021/Utsa_20.png",
  },
];

export const membersData2022 = [
  {
    tag: "Batch 2022",
    name: "Namrita",
    batch: "MCA'22",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2022/Namrita_22.jpg",
  },
  {
    tag: "Batch 2022",
    name: "Ankur",
    batch: "MCA'22",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2022/Ankur_22.jpg",
  },
  {
    tag: "Batch 2022",
    name: "Vishesh",
    batch: "MCA'22",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2022/Vishesh_22.png",
  },
  {
    tag: "Batch 2022",
    name: "Ravindra",
    batch: "MCA'22",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2022/Ravindra_22.jpg",
  },
];

export const membersData2023 = [
  {
    tag: "Batch 2023",
    name: "Aayushi",
    batch: "MCA'23",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2023/Aayushi_23.jpg",
  },
  {
    tag: "Batch 2023",
    name: "Mohit",
    batch: "MSC'22",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2023/Mohit_22.jpg",
  },
  {
    tag: "Batch 2023",
    name: "Pankaj",
    batch: "MCA'23",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2023/Pankaj_23.jpg",
  },
  {
    tag: "Batch 2023",
    name: "Suruchi",
    batch: "MCA'23",
    position: "Member",
    linkedin: "unavailable",
    imagePath: "./images/members/2023/Suruchi_23.jpg",
  },
];

export const membersData2025 = [
  {
    tag: "Batch 2025",
    name: "Chirag Agarwal",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://www.linkedin.com/in/chirag-agarwal-bb82a0198/",
    imagePath: "./images/members/2025/25_chirag.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Ashish Yogi",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://in.linkedin.com/in/ashish-yogi-bb7b28169",
    imagePath: "./images/members/2025/25_Ashish.png",
  },
  {
    tag: "Batch 2025",
    name: "P Janardhan",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://www.linkedin.com/in/pjanardhan7u",
    imagePath: "./images/members/2025/25_Janardhan.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Naman jain",
    position: "Member",
    batch: "MCA'25",
    linkedin:
      "https://www.linkedin.com/in/naman-jain-9794b61b8?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imagePath: "./images/members/2025/25_Naman.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Prasanjeet Karmakar",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://www.linkedin.com/in/prasanjeet-karmakar-783067211/",
    imagePath: "./images/members/2025/25_Prasanjeet.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Surandra Meena",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://in.linkedin.com/in/surandra-meena",
    imagePath: "./images/members/2025/25_Surandra.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Himanshu Upadhyay",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://www.linkedin.com/in/himanshu-upadhyay-851ab4200/",
    imagePath: "./images/members/2025/25_Upadhyay.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Vedansh Rashinkar",
    position: "Member",
    batch: "MCA'25",
    linkedin: "https://www.linkedin.com/in/vedansh-rashinkar/",
    imagePath: "./images/members/2025/25_Vedansh.jpg",
  },
  {
    tag: "Batch 2025",
    name: "Vikash Patel",
    position: "Member",
    batch: "MCA'25",
    linkedin:
      "https://www.linkedin.com/in/vikash-patel-816a6b24a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imagePath: "./images/members/2025/25_Vikash.jpg",
  },
];

export const membersData2026 = [
  {
    tag: "Batch 2026",
    name: "Vivek Kumar",
    position: "Member",
    batch: "MCA'26",
    linkedin: "https://www.linkedin.com/in/vivekkumaryadaav/",
    imagePath: "./images/members/2026/26_Vivek.jpeg",
  },
  {
    tag: "Batch 2026",
    name: "Altaf Hussain",
    position: "Member",
    batch: "MCA'26",
    linkedin: "https://www.linkedin.com/in/altaf-hussain-839400287/",
    imagePath: "./images/members/2026/26_Altaf.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Amit Phougat",
    position: "Member",
    batch: "MCA'26",
    linkedin:
      "https://www.linkedin.com/in/amit-phougat-23a835285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imagePath: "./images/members/2026/26_Amit.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Nimesh Kumar Nadar",
    position: "Member",
    batch: "MCA'26",
    linkedin: "https://linkedin.com/in/nimeshkumarnadar",
    imagePath: "./images/members/2026/26_Nimesh.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Nisha Dhakad",
    position: "Member",
    batch: "MCA'26",
    linkedin: "https://www.linkedin.com/in/nisha-dhakad-59b1a921a/",
    imagePath: "./images/members/2026/26_Nisha.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Veeresh Pratap Singh",
    position: "Member",
    batch: "MSC'25",
    linkedin: "https://www.linkedin.com/in/veeresh-singh-9a1217229",
    imagePath: "./images/members/2026/msc_25_VEERESH.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Shrey Patel",
    position: "Member",
    batch: "MCA'26",
    linkedin: "https://www.linkedin.com/in/shrey-patel-9b697b214/",
    imagePath: "./images/members/2026/26_Shrey.jpeg",
  },
  {
    tag: "Batch 2026",
    name: "Abhishek Maurya",
    position: "Member",
    batch: "MSC'25",
    linkedin: "https://www.linkedin.com/in/abhishek-maurya-dl/",
    imagePath: "./images/members/2026/msc_25Abhishek.jpg",
  },
  {
    tag: "Batch 2026",
    name: "Anushree Jha",
    position: "Member",
    batch: "MSC'25",
    linkedin: "https://www.linkedin.com/in/anushree-jha-400a161a2/",
    imagePath: "./images/members/2026/msc_25anushree.jpeg",
  },
  {
    tag: "Batch 2026",
    name: "Vidit Tomar",
    position: "Member",
    batch: "MSC'25",
    linkedin: "linkedin.com/in/vidit-tomar",
    imagePath: "./images/members/2026/msc_25Vidit.jpg",
  },
];
